<script setup>
import {ref} from 'vue'
import {apiGet,apiSend} from '../api/client'
const expanded=ref(false),rows=ref([]),q=ref(''),page=ref(1),total=ref(0),busy=ref(false),error=ref(''),confirmRow=ref(null)
async function load(p=1){page.value=p;busy.value=true;error.value='';try{const data=await apiGet(`/api/customer-portal/admin/registrations?q=${encodeURIComponent(q.value)}&page=${p}`);rows.value=data.rows;total.value=data.total}catch(e){error.value=e.message}finally{busy.value=false}}
function toggle(){expanded.value=!expanded.value;if(expanded.value)load()}
async function disable(){if(!confirmRow.value)return;busy.value=true;try{await apiSend(`/api/customer-portal/admin/registrations/${confirmRow.value.mini_user_id}/disable`,{method:'POST',body:{}});confirmRow.value=null;await load(page.value)}catch(e){error.value=e.message}finally{busy.value=false}}
function manual(){window.dispatchEvent(new CustomEvent('kferp:navigate-view',{detail:{key:'beanListCenterManual',returnNavigation:{key:'customerPortalSettings',label:'返回客户门户配置'}}}))}
</script>
<template><section class="registrations"><div class="head"><h2>登记用户</h2><button @click="toggle">{{expanded?'收起':'查看登记用户'}}</button><button @click="manual">豆单中心手册</button></div><p>授权手机号并填写昵称的访客，不会自动创建客户档案。订单和专属价格仍按客户权限开放。</p><template v-if="expanded"><form @submit.prevent="load()"><input v-model="q" placeholder="昵称或已验证手机号"/><button :disabled="busy">查询</button></form><p v-if="error" role="alert">{{error}}</p><div class="table"><table><thead><tr><th>昵称</th><th>已验证手机号</th><th>登记时间</th><th>最近访问</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.mini_user_id"><td>{{r.nickname}}</td><td>{{r.verified_phone}}</td><td>{{r.created_at?.slice(0,16).replace('T',' ')}}</td><td>{{r.last_seen_at?.slice(0,16).replace('T',' ')}}</td><td>{{r.active?'有效':'停用'}}</td><td><button v-if="r.active" :disabled="busy" @click="confirmRow=r">停用</button></td></tr></tbody></table></div><p v-if="!rows.length&&!busy">暂无登记用户</p><div class="head"><button :disabled="page<=1||busy" @click="load(page-1)">上一页</button><span>第 {{page}} 页 · 共 {{total}} 人</span><button :disabled="page*30>=total||busy" @click="load(page+1)">下一页</button></div></template><div v-if="confirmRow" role="alert"><p>停用“{{confirmRow.nickname}}”后，该小程序账号的现有会话立即失效，不能重新登记恢复。确认停用？</p><button :disabled="busy" @click="disable">确认停用</button><button :disabled="busy" @click="confirmRow=null">取消</button></div></section></template>
<style scoped>.registrations{background:#fff;border:1px solid #d7e1d8;padding:22px;border-radius:12px;margin-bottom:20px}.head{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.head h2{margin:0;margin-right:auto}p{color:#647567;line-height:1.6}button,input{padding:9px 14px;border:1px solid #c6d7ca;border-radius:7px;background:white;color:#30523b}form{display:flex;gap:10px;flex-wrap:wrap}.table{overflow:auto;margin:16px 0}table{width:100%;min-width:650px;text-align:left;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #e3e8e2}button:disabled{opacity:.5}</style>
