import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(resolve(path), 'utf8')
}

describe('customer inventory miniapp pages', () => {
  it('keeps customer-owned inventory searchable, typed, traceable and reusable for processing requests', () => {
    const panel = source('src/components/CustomerInventoryPanel.vue')

    expect(panel).toContain('fetchCustomerAssetInventory(props.token, activeType.value, query.value)')
    expect(panel).toContain("{ key: 'finished_product', label: '成品' }")
    expect(panel).toContain("{ key: 'green_bean', label: '生豆' }")
    expect(panel).toContain("{ key: 'packaging', label: '包材' }")
    expect(panel).toContain("{ key: 'semi_finished', label: '半成品' }")
    expect(panel).toContain('搜索名称、编码或规格')
    expect(panel).toContain('@tap.stop="toggleSelection(item)"')
    expect(panel).toContain('带入生产工单')
    expect(panel).toContain('processingPrefill.stage')
    expect(panel).toContain('selectedByKey')
    expect(panel).toContain('let loadVersion = 0')
    expect(panel).toContain('if (version !== loadVersion) return')
    expect(panel).toContain('if (navigating.value || !selectedItems.value.length) return')
    expect(panel).toContain('查看批次与流水')
    expect(panel).toContain('fetchCustomerAssetInventoryLedger')
    expect(panel).toContain('质量状态')
    expect(panel).toContain('生产中数量不计入可用库存')
    expect(panel).not.toContain('上一页')
    expect(panel).not.toContain('下一页')
  })

  it('registers a separate inventory detail page with native stack navigation', () => {
    const pages = source('src/pages.json')
    const detail = source('src/pages/customer-inventory-detail/customer-inventory-detail.vue')

    expect(pages).toContain('pages/customer-inventory-detail/customer-inventory-detail')
    expect(detail).toContain('EnvironmentBadge')
    expect(detail).toContain('fetchCustomerInventory')
    expect(detail).toContain('fetchCustomerInventoryBatches')
    expect(detail).toContain('历史库存，暂无生产日期')
    expect(detail).toContain('提交生产工单')
    expect(detail).toContain('使用现货下单')
    expect(detail).toContain('订单占用')
    expect(detail).toContain('现货可用')
    expect(detail).toContain('未入库可预订')
    expect(detail).toContain('sourceRequestLines')
    expect(detail).toContain('本规格申请')
    expect(detail).toContain('source_stock_entry_no')
    expect(detail).toContain('source_work_order_no')
    expect(detail).toContain('related_orders')
    expect(detail).toContain('processingPrefill.stage')
    expect(detail).toContain('if (navigating.value) return')
    expect(detail).toContain('let loadVersion = 0')
    expect(detail).toContain('version !== loadVersion')
    expect(detail).toContain('customerID !== session.currentCustomerID')
    expect(detail).toContain('当前库存已变化，请返回库存列表刷新')
    expect(detail).toContain('batches.value = []')
    expect(detail).toContain('v-if="summary"')
    expect(detail).toContain("query?.bom_spec_id")
    expect(detail).toContain("query?.bom_variant_id")
    expect(detail).toContain('bom_spec_id: bomSpecID.value')
    expect(detail).toContain('bom_variant_id: bomVariantID.value')
    expect(detail).toContain('inventory_unit: inventoryUnit.value')
    expect(detail).toContain("uni.navigateTo({")
    expect(detail).not.toContain('uni.redirectTo')
    expect(detail).not.toContain('uni.reLaunch')
  })

  it('consumes multi-spec prefills once and preserves both canonical and legacy single-item queries', () => {
    const service = source('src/pages/service/service.vue')
    const processing = source('src/components/CustomerProcessingPanel.vue')

    expect(service).toContain('processingPrefill.consume')
    expect(service).toContain("query?.product_id")
    expect(service).toContain("query?.spec_g")
    expect(service).toContain("query?.bom_spec_id")
    expect(service).toContain("query?.bom_variant_id")
    expect(service).toContain(':prefill-bom-spec-id="prefillBomSpecID"')
    expect(service).toContain(':prefill-bom-variant-id="prefillBomVariantID"')
    expect(service).toContain(':prefill-items="processingPrefillItems"')
    expect(service).toContain('@prefill-consumed="clearProcessingPrefill"')
    expect(processing).toContain('resolveProcessingPrefillLines')
    expect(processing).toContain('prefillApplied')
    expect(processing).toContain("emit('prefillConsumed')")
    expect(processing).toContain('未配置有效 BOM')
  })
})
