FROM docker.m.daocloud.io/library/golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go env -w GOPROXY=https://goproxy.cn,direct && go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/orderapp ./

FROM docker.m.daocloud.io/library/alpine:3.20
WORKDIR /app
COPY --from=build /out/orderapp /app/orderapp
COPY templates /app/templates
EXPOSE 8080
ENV LISTEN=:8080
CMD ["/app/orderapp"]
