package productcreator

import (
	"context"
	"testing"

	bomapp "orderapp/internal/application/bom"
	creatorapp "orderapp/internal/application/productcreator"
)

type specTemplatePreviewRepository struct {
	bomapp.Repository
	bomapp.ProductionBomSpecRepository
	templates []bomapp.ProductionBomSpecTemplate
}

func (r specTemplatePreviewRepository) ListProductionBomSpecTemplates(context.Context) ([]bomapp.ProductionBomSpecTemplate, error) {
	return r.templates, nil
}

func (r specTemplatePreviewRepository) GetProductionBomSpecTemplate(_ context.Context, templateID, versionID int64) (bomapp.ProductionBomSpecTemplate, error) {
	for _, template := range r.templates {
		if template.ID == templateID {
			for _, version := range template.Versions {
				if version.ID == versionID {
					copy := template
					copy.Versions = []bomapp.ProductionBomSpecTemplateVersion{version}
					copy.Variants = template.Variants
					return copy, nil
				}
			}
		}
	}
	return bomapp.ProductionBomSpecTemplate{}, context.Canceled
}

func TestProductBOMTemplatePreviewValidatesGeneratedProductSpecificationIdentity(t *testing.T) {
	repo := specTemplatePreviewRepository{templates: []bomapp.ProductionBomSpecTemplate{
		previewSpecTemplate(11, 91, "半成品规格", "semi-200g"),
		previewSpecTemplate(12, 92, "成品规格", "finished-200g"),
	}}
	executor := BusinessExecutor{bom: bomapp.NewService(repo)}
	run := creatorapp.Run{
		Workflow: creatorapp.Workflow{Version: 4, Nodes: []creatorapp.Node{
			{ID: "raw", Kind: creatorapp.ModuleMaterial, Name: "原料", Config: map[string]any{"data_role": "input"}},
			{ID: "semi-bom", Kind: creatorapp.ModuleBOM, Name: "半成品 BOM", Config: map[string]any{"output_type": "product", "spec_template_version_id": 91}},
			{ID: "semi-product", Kind: creatorapp.ModuleProduct, Name: "半成品商品", Config: map[string]any{"data_role": "output"}},
			{ID: "finished-bom", Kind: creatorapp.ModuleBOM, Name: "成品包装 BOM", Config: map[string]any{"output_type": "product", "spec_template_version_id": 92}},
			{ID: "finished-product", Kind: creatorapp.ModuleProduct, Name: "成品", Config: map[string]any{"data_role": "output"}},
		}, Edges: []creatorapp.Edge{
			{ID: "raw-source", Source: "raw", SourceHandle: "material", Target: "semi-bom", TargetHandle: "components", Kind: creatorapp.EdgeData},
			{ID: "semi-output", Source: "semi-bom", SourceHandle: "assembly", Target: "semi-product", TargetHandle: "from_bom", Kind: creatorapp.EdgeData},
			{ID: "semi-spec", Source: "semi-product", SourceHandle: "specs", Target: "finished-bom", TargetHandle: "components:source:semi-spec", Kind: creatorapp.EdgeData},
			{ID: "finished-output", Source: "finished-bom", SourceHandle: "assembly", Target: "finished-product", TargetHandle: "from_bom", Kind: creatorapp.EdgeData},
		}},
		Inputs: map[string]map[string]any{
			"raw":          {"rows": []any{map[string]any{"row_id": "raw-row", "name": "原料", "unit": "kg"}}},
			"semi-bom":     {"main_input_source_node_id": "raw", "main_input_source_row_id": "raw-row"},
			"finished-bom": {"main_input_source_node_id": "semi-product", "main_input_source_row_id": "semi-200g"},
		},
	}

	details, issues := executor.InspectConfigurationPreview(context.Background(), run)
	if len(issues) != 0 {
		t.Fatalf("published upstream product specification should be a valid BOM main input, got %+v", issues)
	}
	finalDetails := details["finished-bom"]
	if finalDetails["specification_template"] == nil || finalDetails["main_input"] == nil {
		t.Fatalf("preview should include the selected template and main-input summary, got %+v", finalDetails)
	}

	run.Inputs["finished-bom"]["main_input_source_row_id"] = "unknown-spec"
	_, issues = executor.InspectConfigurationPreview(context.Background(), run)
	if !previewHasCode(issues, "main_input_row_invalid") {
		t.Fatalf("preview must reject a specification row not generated by its connected upstream BOM, got %+v", issues)
	}

	run.Inputs["finished-bom"]["main_input_source_row_id"] = "semi-200g"
	repo.templates[1].Variants[0].Items = []bomapp.ProductionBomSpecTemplateVariantDraftItem{{ProductionBomDraftItem: bomapp.ProductionBomDraftItem{ConsumeUnit: "ratio_pct", RatioPct: 15}, IsMainInput: true}}
	executor = BusinessExecutor{bom: bomapp.NewService(repo)}
	_, issues = executor.InspectConfigurationPreview(context.Background(), run)
	if !previewHasCode(issues, "product_main_input_requires_fixed_template") {
		t.Fatalf("a product main input must be rejected when the selected template uses proportional recipe loss, got %+v", issues)
	}
}

func previewSpecTemplate(id, versionID int64, name, specKey string) bomapp.ProductionBomSpecTemplate {
	return bomapp.ProductionBomSpecTemplate{
		ID: id, Name: name, Active: true,
		Versions: []bomapp.ProductionBomSpecTemplateVersion{{ID: versionID, TemplateID: id, VersionNo: "V001", Status: "published", VariantCount: 1}},
		Variants: []bomapp.ProductionBomSpecTemplateVariant{{SpecKey: specKey, Name: "200g", InventoryUnit: "袋", IsDefault: true}},
	}
}

func previewHasCode(issues []creatorapp.ValidationIssue, code string) bool {
	for _, issue := range issues {
		if issue.Code == code {
			return true
		}
	}
	return false
}
