package productcreator

import (
	"context"
	"fmt"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"

	bomapp "orderapp/internal/application/bom"
	creatorapp "orderapp/internal/application/productcreator"
	postgresinfra "orderapp/internal/infrastructure/postgres"

	"github.com/jackc/pgx/v5/pgxpool"
)

type specTemplatePreviewRepository struct {
	bomapp.Repository
	bomapp.ProductionBomSpecRepository
	templates []bomapp.ProductionBomSpecTemplate
}

func (r specTemplatePreviewRepository) ListProductionBomSpecTemplates(context.Context) ([]bomapp.ProductionBomSpecTemplate, error) {
	return r.templates, nil
}

func (r specTemplatePreviewRepository) GetProductionBomSpecTemplate(_ context.Context, templateID, versionID int64) (bomapp.ProductionBomSpecTemplate, error) {
	for _, template := range r.templates {
		if template.ID == templateID {
			for _, version := range template.Versions {
				if version.ID == versionID {
					copy := template
					copy.Versions = []bomapp.ProductionBomSpecTemplateVersion{version}
					copy.Variants = template.Variants
					return copy, nil
				}
			}
		}
	}
	return bomapp.ProductionBomSpecTemplate{}, context.Canceled
}

func TestProductBOMTemplatePreviewValidatesGeneratedProductSpecificationIdentity(t *testing.T) {
	repo := specTemplatePreviewRepository{templates: []bomapp.ProductionBomSpecTemplate{
		previewSpecTemplate(11, 91, "半成品规格", "semi-200g"),
		previewSpecTemplate(12, 92, "成品规格", "finished-200g"),
	}}
	executor := BusinessExecutor{bom: bomapp.NewService(repo)}
	run := creatorapp.Run{
		Workflow: creatorapp.Workflow{Version: 4, Nodes: []creatorapp.Node{
			{ID: "raw", Kind: creatorapp.ModuleMaterial, Name: "原料", Config: map[string]any{"data_role": "input"}},
			{ID: "semi-bom", Kind: creatorapp.ModuleBOM, Name: "半成品 BOM", Config: map[string]any{"output_type": "product", "spec_template_version_id": 91}},
			{ID: "semi-product", Kind: creatorapp.ModuleProduct, Name: "半成品商品", Config: map[string]any{"data_role": "output"}},
			{ID: "finished-bom", Kind: creatorapp.ModuleBOM, Name: "成品包装 BOM", Config: map[string]any{"output_type": "product", "spec_template_version_id": 92}},
			{ID: "finished-product", Kind: creatorapp.ModuleProduct, Name: "成品", Config: map[string]any{"data_role": "output"}},
		}, Edges: []creatorapp.Edge{
			{ID: "raw-source", Source: "raw", SourceHandle: "material", Target: "semi-bom", TargetHandle: "components", Kind: creatorapp.EdgeData},
			{ID: "semi-output", Source: "semi-bom", SourceHandle: "assembly", Target: "semi-product", TargetHandle: "from_bom", Kind: creatorapp.EdgeData},
			{ID: "semi-spec", Source: "semi-product", SourceHandle: "specs", Target: "finished-bom", TargetHandle: "components:source:semi-spec", Kind: creatorapp.EdgeData},
			{ID: "finished-output", Source: "finished-bom", SourceHandle: "assembly", Target: "finished-product", TargetHandle: "from_bom", Kind: creatorapp.EdgeData},
		}},
		Inputs: map[string]map[string]any{
			"raw":          {"rows": []any{map[string]any{"row_id": "raw-row", "name": "原料", "unit": "kg"}}},
			"semi-bom":     {"main_input_source_node_id": "raw", "main_input_source_row_id": "raw-row"},
			"finished-bom": {"main_input_source_node_id": "semi-product", "main_input_source_row_id": "semi-200g"},
		},
	}

	details, issues := executor.InspectConfigurationPreview(context.Background(), run)
	if len(issues) != 0 {
		t.Fatalf("published upstream product specification should be a valid BOM main input, got %+v", issues)
	}
	finalDetails := details["finished-bom"]
	if finalDetails["specification_template"] == nil || finalDetails["main_input"] == nil {
		t.Fatalf("preview should include the selected template and main-input summary, got %+v", finalDetails)
	}

	run.Inputs["finished-bom"]["main_input_source_row_id"] = "unknown-spec"
	_, issues = executor.InspectConfigurationPreview(context.Background(), run)
	if !previewHasCode(issues, "main_input_row_invalid") {
		t.Fatalf("preview must reject a specification row not generated by its connected upstream BOM, got %+v", issues)
	}

	run.Inputs["finished-bom"]["main_input_source_row_id"] = "semi-200g"
	repo.templates[1].Variants[0].Items = []bomapp.ProductionBomSpecTemplateVariantDraftItem{{ProductionBomDraftItem: bomapp.ProductionBomDraftItem{ConsumeUnit: "ratio_pct", RatioPct: 15}, IsMainInput: true}}
	executor = BusinessExecutor{bom: bomapp.NewService(repo)}
	_, issues = executor.InspectConfigurationPreview(context.Background(), run)
	if !previewHasCode(issues, "product_main_input_requires_fixed_template") {
		t.Fatalf("a product main input must be rejected when the selected template uses proportional recipe loss, got %+v", issues)
	}
}

func TestV5BOMPreviewShowsSharedConnectedRouteAndOverridesEveryProductVariant(t *testing.T) {
	dsn := strings.TrimSpace(os.Getenv("ORDERAPP_TEST_DATABASE_URL"))
	if dsn == "" {
		dsn = strings.TrimSpace(os.Getenv("DATABASE_URL"))
	}
	if dsn == "" {
		t.Skip("ORDERAPP_TEST_DATABASE_URL or DATABASE_URL is required for product creator postgres tests")
	}
	ctx := context.Background()
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer pool.Close()
	schema := fmt.Sprintf("test_product_creator_v5_route_preview_%d", time.Now().UnixNano())
	if _, err := pool.Exec(ctx, "CREATE SCHEMA "+schema); err != nil {
		t.Fatal(err)
	}
	defer func() { _, _ = pool.Exec(context.Background(), "DROP SCHEMA IF EXISTS "+schema+" CASCADE") }()
	if _, err := pool.Exec(ctx, fmt.Sprintf(`
		CREATE TABLE %s.process_routes(id BIGINT PRIMARY KEY, name TEXT NOT NULL, status TEXT NOT NULL);
		INSERT INTO %s.process_routes(id,name,status) VALUES(31,'规格模板工艺 200g','active'),(32,'规格模板工艺 500g','active'),(73,'共享工艺路线','active');
	`, schema, schema)); err != nil {
		t.Fatal(err)
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()
	ctx = postgresinfra.WithTransaction(ctx, tx)

	template := previewSpecTemplate(12, 92, "成品规格", "finished-200g")
	template.Variants = append(template.Variants, bomapp.ProductionBomSpecTemplateVariant{
		SpecKey: "finished-500g", Name: "500g", InventoryUnit: "袋", ProcessRouteID: 32,
	})
	template.Variants[0].ProcessRouteID = 31
	repo := specTemplatePreviewRepository{templates: []bomapp.ProductionBomSpecTemplate{template}}
	executor := BusinessExecutor{schema: schema, pool: pool, bom: bomapp.NewService(repo)}
	run := creatorapp.Run{
		Workflow: creatorapp.Workflow{Version: 5, Nodes: []creatorapp.Node{
			{ID: "route", Kind: creatorapp.ModuleProcess, Name: "共享工艺", Config: map[string]any{"route_id": 73}},
			{ID: "material-bom", Kind: creatorapp.ModuleBOM, Name: "半成品烘焙 BOM", Config: map[string]any{"output_type": "material"}},
			{ID: "product-bom", Kind: creatorapp.ModuleBOM, Name: "成品包装 BOM", Config: map[string]any{"output_type": "product", "spec_template_version_id": 92}},
		}, Edges: []creatorapp.Edge{
			{ID: "route-material", Source: "route", SourceHandle: "route", Target: "material-bom", TargetHandle: "route", Kind: creatorapp.EdgeData},
			{ID: "route-product", Source: "route", SourceHandle: "route", Target: "product-bom", TargetHandle: "route", Kind: creatorapp.EdgeData},
		}},
		Inputs: map[string]map[string]any{
			"route":        {"route_id": 73},
			"material-bom": {"route_override_id": 0},
			"product-bom":  {"route_override_id": 0},
		},
	}

	// The API preview path runs outside a write transaction. Route inspection
	// must therefore use the repository pool instead of assuming a tx in ctx.
	outsideTxDetails, outsideTxIssues := executor.InspectConfigurationPreview(context.Background(), run)
	if len(outsideTxIssues) != 0 {
		t.Fatalf("active shared routes should preview outside a transaction, got %+v", outsideTxIssues)
	}
	for _, nodeID := range []string{"material-bom", "product-bom"} {
		selection, ok := outsideTxDetails[nodeID]["process_route"].(map[string]any)
		if !ok || selection["id"] != int64(73) || selection["name"] != "共享工艺路线" || selection["source"] != "connected_node" {
			t.Fatalf("outside-transaction route preview for %s=%+v, want the shared route", nodeID, outsideTxDetails[nodeID]["process_route"])
		}
	}
	productTemplate := outsideTxDetails["product-bom"]["specification_template"].(map[string]any)
	outsideTxVariants := productTemplate["variants"].([]bomapp.ProductionBomSpecTemplateVariant)
	if !reflect.DeepEqual([]string{outsideTxVariants[0].ProcessRouteName, outsideTxVariants[1].ProcessRouteName}, []string{"共享工艺路线", "共享工艺路线"}) {
		t.Fatalf("outside-transaction preview should resolve the route name for every product spec, got %+v", outsideTxVariants)
	}

	details, issues := executor.InspectConfigurationPreview(ctx, run)
	if len(issues) != 0 {
		t.Fatalf("active route shared by material and product BOMs should preview cleanly, got %+v", issues)
	}
	for _, nodeID := range []string{"material-bom", "product-bom"} {
		selection, ok := details[nodeID]["process_route"].(map[string]any)
		if !ok || selection["id"] != int64(73) || selection["name"] != "共享工艺路线" || selection["source"] != "connected_node" {
			t.Fatalf("%s process route preview=%+v, want connected shared route", nodeID, details[nodeID]["process_route"])
		}
	}
	productDetail := details["product-bom"]["specification_template"].(map[string]any)
	variants := productDetail["variants"].([]bomapp.ProductionBomSpecTemplateVariant)
	if len(variants) != 2 || !reflect.DeepEqual([]int64{variants[0].ProcessRouteID, variants[1].ProcessRouteID}, []int64{73, 73}) || !reflect.DeepEqual([]string{variants[0].ProcessRouteName, variants[1].ProcessRouteName}, []string{"共享工艺路线", "共享工艺路线"}) || !reflect.DeepEqual([]string{variants[0].ProcessRouteSource, variants[1].ProcessRouteSource}, []string{"connected_node", "connected_node"}) {
		t.Fatalf("connected route should apply to every generated product spec in preview: %+v", variants)
	}

	run.Workflow.Edges = run.Workflow.Edges[:1]
	run.Inputs["product-bom"]["route_override_id"] = 0
	details, issues = executor.InspectConfigurationPreview(ctx, run)
	if len(issues) != 0 {
		t.Fatalf("active per-specification template routes should preview cleanly after removing the shared route, got %+v", issues)
	}
	productDetail = details["product-bom"]["specification_template"].(map[string]any)
	variants = productDetail["variants"].([]bomapp.ProductionBomSpecTemplateVariant)
	if !reflect.DeepEqual([]int64{variants[0].ProcessRouteID, variants[1].ProcessRouteID}, []int64{31, 32}) || !reflect.DeepEqual([]string{variants[0].ProcessRouteName, variants[1].ProcessRouteName}, []string{"规格模板工艺 200g", "规格模板工艺 500g"}) || !reflect.DeepEqual([]string{variants[0].ProcessRouteSource, variants[1].ProcessRouteSource}, []string{"specification_template", "specification_template"}) {
		t.Fatalf("removing the shared route should restore each named specification-template route: %+v", variants)
	}
}

func TestV5ProductBOMPreviewPreservesPerVariantTemplateRoutesWithoutOverride(t *testing.T) {
	template := previewSpecTemplate(12, 92, "成品规格", "finished-200g")
	template.Variants = append(template.Variants, bomapp.ProductionBomSpecTemplateVariant{
		SpecKey: "finished-500g", Name: "500g", InventoryUnit: "袋", ProcessRouteID: 32,
	})
	template.Variants[0].ProcessRouteID = 31
	run := creatorapp.Run{
		Workflow: creatorapp.Workflow{Version: 5, Nodes: []creatorapp.Node{{ID: "product-bom", Kind: creatorapp.ModuleBOM, Name: "成品包装 BOM", Config: map[string]any{"output_type": "product", "spec_template_version_id": 92}}}},
		Inputs:   map[string]map[string]any{"product-bom": {"route_override_id": 0}},
	}
	executor := BusinessExecutor{bom: bomapp.NewService(specTemplatePreviewRepository{templates: []bomapp.ProductionBomSpecTemplate{template}})}
	details, issues := executor.InspectConfigurationPreview(context.Background(), run)
	if len(issues) != 0 {
		t.Fatalf("following specification-template routes should preview cleanly, got %+v", issues)
	}
	selection := details["product-bom"]["process_route"].(map[string]any)
	if selection["source"] != "specification_template" || selection["name"] != "规格模板各规格默认工艺" {
		t.Fatalf("route summary=%+v, want per-specification template defaults", selection)
	}
	productDetail := details["product-bom"]["specification_template"].(map[string]any)
	variants := productDetail["variants"].([]bomapp.ProductionBomSpecTemplateVariant)
	if got := []int64{variants[0].ProcessRouteID, variants[1].ProcessRouteID}; !reflect.DeepEqual(got, []int64{31, 32}) {
		t.Fatalf("without an override each spec must keep its own template route, got %+v", got)
	}
}

func previewSpecTemplate(id, versionID int64, name, specKey string) bomapp.ProductionBomSpecTemplate {
	return bomapp.ProductionBomSpecTemplate{
		ID: id, Name: name, Active: true,
		Versions: []bomapp.ProductionBomSpecTemplateVersion{{ID: versionID, TemplateID: id, VersionNo: "V001", Status: "published", VariantCount: 1}},
		Variants: []bomapp.ProductionBomSpecTemplateVariant{{SpecKey: specKey, Name: "200g", InventoryUnit: "袋", IsDefault: true}},
	}
}

func previewHasCode(issues []creatorapp.ValidationIssue, code string) bool {
	for _, issue := range issues {
		if issue.Code == code {
			return true
		}
	}
	return false
}
